name: Rust Tests

on:
  push:

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

# Concurrency is employed to avoid multiple identical workflows from running concurrently. When a new event is triggered
# while this workflow is active, the new workflow will be executed, and the previous one will be terminated. It's
# important to note that the group is the current ref, typically the current branch, and as a result, different branches
# won't affect each other.
concurrency:
  group: ${{ github.ref }}-rust-test
  cancel-in-progress: true

jobs:
  rust_tests:
    name: Rust Tests for ${{ matrix.os }}

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: "x86_64-unknown-linux-gnu"
            toolchain_components: "clippy, rustfmt"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        name: Cloning repo
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Extract Rust Toolchain
        shell: bash
        id: toolchain
        run: |
          version=$(grep -Eo 'channel = \"[0-9\.]+\"' rust-toolchain.toml | grep -Eo '[0-9\.]+')
          echo "version=$version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: ${{ matrix.toolchain_components }}
          toolchain: ${{ steps.toolchain.outputs.version }}
          targets: ${{ matrix.target }}

      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: Tests
        run: cargo test --release
